exp_name: my_experiment
mode: lora
num_images_to_train: 4500
pretrained_model_path: 'dreamlike-art/dreamlike-photoreal-2.0'
lora_rank: 4
output_dir: ./stable-diffusion-2
seed: 0
learning_rate: 1e-5
train_batch_size: 4
max_train_steps: 22000
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-3
adam_epsilon: 1e-08
max_grad_norm: 1.0
lr_scheduler: constant
lr_warmup_steps: 500
#mixed_precision: fp16
scale_lr: False
gradient_accumulation_steps: 8
gradient_checkpointing: False
checkpointing_step_interv: 2000
validation_step_interv: 1000
resume_from_checkpoint: null
enable_xformers_memory_efficient_attention: True
num_inference_steps: 20
num_validation_images: 8
validation_prompt: "A kitti_scene of roads with vehicles, pedestrians, road signs, grass, trees, and buildings, captured from a moving vehicle under various environmental and weather conditions."
 # Updated to match KITTI dataset
guidance_scale: 9.0
negative_prompt: "abstract, cartoon, low resolution, unrealistic, fantasy elements, distorted perspective, blurry, overexposed, night scenes, extreme weather, futuristic vehicles, animals, flying objects, underwater, low-quality textures, unnatural colors, alien landscapes, incorrect proportions, fantasy characters, sci-fi buildings, otherworldly environments,long exposure, unnatural lighting, blur, distorted vehciles,blurry cars, out-of-focus vehicles, distorted vehicles, low-detail cars, low-resolution cars, incorrect road signs, abstract signs, low-detail signs, unrealistic road signs, distorted text on signs, cartoon grass, fake grass, unrealistic vegetation, overly bright grass, low-texture grass, artificial grass, 2D grass, heavy shadows, overly dark shadows, unnatural lighting, harsh shadows, extreme shadow contrast, underexposed."  # Updated to avoid common visual problems in urban scenes
data_root: '/data/iqra/datasets/kitti/data_object_image_3/training/'

